#   https://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
os: linux
files:
  - source: tools
    destination: /home/ec2-user/pur-draft/tools
  - source: templates
    destination: /home/ec2-user/pur-draft/templates
  - source: deploy_scripts
    destination: /home/ec2-user/pur-draft/deploy_scripts
  - source: xform
    destination: /home/ec2-user/pur-draft/xform
  - source: app.py
    destination: /home/ec2-user/pur-draft
  - source: requirements.txt
    destination: /home/ec2-user/pur-draft
  - source: .env
    destination: /home/ec2-user/pur-draft
permissions:
  - object: /home/ec2-user/pur-draft
    pattern: "**"
    owner: ec2-user
    group: ec2-user
# If you are not running any commands on the Amazon EC2 instance, then remove
#   the "hooks" section altogether. A blank or incomplete "hooks" section
#   may cause associated deployments to fail.
hooks:
  ApplicationStop:
    - location: deploy_scripts/stop.sh
      runas: ec2-user
  BeforeInstall:
    - location: deploy_scripts/preinstall.sh
      runas: ec2-user
  AfterInstall:
    - location: deploy_scripts/postinstall.sh
      runas: ec2-user
  ApplicationStart:
    - location: deploy_scripts/start.sh
      runas: ec2-user
